remote_theme: "mmistakes/minimal-mistakes@4.19.3"
title: Mable Wang

minimal_mistakes_skin: "mint"
search: true
breadcrumbs: true
read_time: false

main:
  - title: "About"
    url: /about/
  - title: "Resume"
    url: /resume/
  - title: "Skills"
    url: /skills/
  - title: "Projects"
    url: /projects/


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme